import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [pkgName, setPkgName] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <form action={`/package/${pkgName}`} method="get">
          <input value={pkgName} onChange={(e) => setPkgName(e.target.value)} />
          <button>Go</button>
        </form>
      </section>
    </>
  );
}
